mutation CreateUser(
    $email: String!
    $password: String!
) {
    createUser(
        input: {
            email: $email
            password: $password
        }
    )
}

mutation LoginUser(
    $email: String!
    $password: String!
) {
    loginUser(
        input: {
            email: $email
            password: $password
        }
    ) {
        userId
        token
        expiresIn
        tokenType
    }
}

mutation LogoutUser($userId: ID!) {
    logoutUser(ID: $userId) {
        userId
    }
}
