query GetProfiles ($userId: String) {
    profiles (where: { userId: $userId }) {
        id
        name
        image
    }
}

mutation CreateProfile($input: ProfileInput!) {
    createProfile(input: $input) {
        id
        name
        image
        userId
    }
}

mutation CreateProfiles($input: [ProfileInput!]!) {
    createProfiles(input: $input) {
        id
        name
        image
        userId
    }
}

mutation UpdateProfile(
    $profileId: ID!
    $name: String!
    $userId: String!
) {
    updateProfile(
        id: $profileId,
        input: {
            name: $name,
            userId: $userId
        }
    ) {
        id
        name
        image
        userId
    }
}
