fragment UserFragment on User {
    id
    name
    email
    token
    image
    createdAt
    updatedAt
    createdById
    updatedById
}

query GetUser($id: ID!) {
    user(ID: $id) {
        ...UserFragment
    }
}

query GetUserRoleAsAnonymous($email: String!) {
    users(where: { email: $email }) {
        id
    }
}
